
package de.wxq.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "HelloWeb", targetNamespace = "http://service.wxq.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWeb {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayGreeting", targetNamespace = "http://service.wxq.com/", className = "com.wxq.service.client.SayGreeting")
    @ResponseWrapper(localName = "sayGreetingResponse", targetNamespace = "http://service.wxq.com/", className = "com.wxq.service.client.SayGreetingResponse")
    public String sayGreeting(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
